# Лабораторная работа 1. Вариант 5 — Криптовалютная биржа (High-Frequency Trading)
## Выполнил студент группы ИУ5-85Б Андрест Владислав

---

## **Содержание**

### **ЧАСТЬ 1. Парето-оптимизация конфигураций серверов**
1. Постановка задачи
2. Загрузка данных
3. Фильтрация по требованиям HFT
4. Парето-оптимизация
5. Нормирование критериев
6. Идеальная точка и расстояние
7. Линейная свертка с приоритетами

### **ЧАСТЬ 2. Масштабирование инфраструктуры**
8. Определение весовых коэффициентов для сегментов
9. Расчет критериев предпочтения для каждого сегмента
10. Требования к сетевой инфраструктуре (10–25G RDMA, 10G для DB)
11. Требования к низкой задержке и ускорению
12. Двухуровневая оптимизация
13. Визуализация результатов
14. Выводы

---
# **ЧАСТЬ 1. ПАРЕТО-ОПТИМИЗАЦИЯ СЕРВЕРНЫХ КОНФИГУРАЦИЙ (HFT)**
---

## 1. Постановка задачи (Часть 1)

Требуется подобрать конфигурации серверов для развёртывания инфраструктуры **криптовалютной биржи (High-Frequency Trading, HFT)**.

**Требования к системе:**

1. **Микросекундные задержки** — минимальное время отклика.
2. **Аппаратное ускорение сетевых операций** — высокопроизводительные сетевые интерфейсы.
3. **Максимальная отказоустойчивость** — резервирование и надёжные компоненты.
4. **Полное резервирование инфраструктуры** — дублирование критических узлов.

**Количественные ограничения:**

- CPU_Cores ≥ 16 (высокая частота и многопоточность).
- RAM_GB ≥ 64 (обработка большого количества ордеров).
- Storage_Type ∈ {SSD, NVMe} (минимальная задержка I/O).
- Network_Speed_Gbps ≥ 10 (низкая сетевая задержка).
- Condition ∈ {Like New, New} (минимизация риска отказов).
- Power_Consumption_W ≤ 800.
- Price_USD ≤ 8000.

---
## 2. Загрузка данных

In [ ]:
# Загрузка необходимых библиотек
if (!require(readxl)) install.packages("readxl", repos = "https://cloud.r-project.org")
if (!require(dplyr)) install.packages("dplyr", repos = "https://cloud.r-project.org")
if (!require(ggplot2)) install.packages("ggplot2", repos = "https://cloud.r-project.org")
if (!require(tidyr)) install.packages("tidyr", repos = "https://cloud.r-project.org")

library(readxl)
library(dplyr)
library(ggplot2)
library(tidyr)

# Загрузка данных из CSV файла
Data <- read.csv("https://raw.githubusercontent.com/junaart/AHP_KIS/refs/heads/main/Lab_1/computer_dataset_1000.csv", sep = ",")
View(Data)
colnames(Data)
cat("Размер датасета:", nrow(Data), "x", ncol(Data), "\n")

# Приводим значения скорости Ethernet к числовым значениям в Gbps
ethernet_speed_value <- as.numeric(gsub("[^0-9.]", "", Data$Ethernet_Speed))

is_gbps <- grepl("gbps", Data$Ethernet_Speed, ignore.case = TRUE)
is_mbps <- grepl("mbps", Data$Ethernet_Speed, ignore.case = TRUE)

# Если явно Gbps — оставляем как есть
# Если явно Mbps или единицы не указаны — считаем что это Mbps и переводим в Gbps
Data$Ethernet_Speed_Gbps <- ifelse(is_gbps, ethernet_speed_value,
                            ifelse(is_mbps, ethernet_speed_value / 1000,
                                   ethernet_speed_value / 1000))

Data$Ethernet_Speed_Gbps <- as.numeric(Data$Ethernet_Speed_Gbps)
summary(Data$Ethernet_Speed_Gbps)

     ID      CPU_Frequency_GHz CPU_Cores CPU_Brand     CPU_Generation RAM_GB
1    PC-0001 2.64               4        Intel Core i9 11               16
2    PC-0002 5.00               8        AMD Ryzen 3    8               16
3    PC-0003 4.10              12        AMD Ryzen 9   12              256
4    PC-0004 3.55              10        Intel Core i7 11               16
5    PC-0005 1.74              12        AMD Ryzen 9    8               16
6    PC-0006 1.74               8        Intel Core i3 14              128
7    PC-0007 1.34               8        AMD Ryzen 7   10               32
8    PC-0008 4.65              12        AMD Ryzen 9    7              128
9    PC-0009 3.56               4        Intel Core i5 11                8
10   PC-0010 4.00               6        Intel Core i9  9               32
11   PC-0011 1.18               4        Intel Core i5 12                4
12   PC-0012 5.08              32        AMD Ryzen 7   12                8
13   PC-0013 4.51              24        AMD Ryzen 3   14              256
14   PC-0014 1.97               2        AMD Ryzen 5   10                8
15   PC-0015 1.85              10        Intel Core i5 10               32
16   PC-0016 1.85              16        Intel Core i5 11               32
17   PC-0017 2.35               4        Intel Core i3  8               16
18   PC-0018 3.25               8        Intel Core i7 10              256
19   PC-0019 2.87              16        AMD Ryzen 5   10                4
20   PC-0020 2.29               2        AMD Ryzen 9    7               64
21   PC-0021 3.61               8        AMD Ryzen 5   10             1024
22   PC-0022 1.67               4        Intel Core i9 12               32
23   PC-0023   NA              16        AMD EPYC      12              512
24   PC-0024 2.60              32        AMD Ryzen 7    7                8
25   PC-0025 2.97              24        Intel Xeon     7               32
26   PC-0026 4.32               6        AMD Ryzen 3    9               16
27   PC-0027 1.92              12        Intel Core i7 12               64
28   PC-0028 3.21              12        Intel Core i3  7             1024
29   PC-0029 3.53               4        AMD Ryzen 7   11               16
30   PC-0030 1.29              12        Intel Core i5  7               64
⋮    ⋮       ⋮                 ⋮         ⋮             ⋮              ⋮
971  PC-0971 3.82               2        AMD Ryzen 7    8               32
972  PC-0972 4.94              12        Intel Core i5 11               16
973  PC-0973 4.10               4        AMD Ryzen 7    7              128
974  PC-0974 1.98               8        AMD Ryzen 9   10               64
975  PC-0975 1.23               4        Intel Core i7 10               32
976  PC-0976 2.18              24        AMD EPYC      10                4
977  PC-0977 3.54               4        Intel Core i3 11              128
978  PC-0978 1.31               6        Intel Core i5 12                4
979  PC-0979 3.14              12        AMD Ryzen 3   12               64
980  PC-0980 3.55              12        AMD Ryzen 5    6             1024
981  PC-0981 2.47               4        AMD Ryzen 5    8               32
982  PC-0982 4.26              12        Intel Core i3 10               16
983  PC-0983 1.54               6        AMD EPYC      13               64
984  PC-0984 1.41               6        Intel Core i3 12              128
985  PC-0985 4.09               4        Intel Core i5 12               32
986  PC-0986 3.13               2        Intel Core i3  9             1024
987  PC-0987 3.92              10        AMD Ryzen 5   10                8
988  PC-0988 2.88               6        Intel Xeon    10               32
989  PC-0989 2.11               6        AMD Ryzen 5    8               64
990  PC-0990 4.46              10        AMD Ryzen 9    6              256
991  PC-0991 4.38              10        Intel Core i3 13               16
992  PC-0992 3.95               4        AMD Ryzen 3    8              128
993  PC-0993 2.22               8        AMD Ryzen 3    8               32
994  PC-0994 3.52               4        AMD Ryzen 3    7               32
995  PC-0995 2.58              10        Intel Core i3 13                8
996  PC-0996 1.48               8        AMD Ryzen 5   10              256
997  PC-0997 4.86              24        AMD Ryzen 3   11               16
998  PC-0998 1.66               2        AMD Ryzen 7   13               16
999  PC-0999 5.00               2        AMD Ryzen 3    9               16
1000 PC-1000 2.93               4        Intel Core i5 11              256
     Storage_GB Storage_Type GPU_Type   GPU_Model           ⋯ Brand
1    1000       SSD          Dedicated  AMD Radeon RX 6600  ⋯ Apple
2    2000       NVMe         Integrated Intel Iris Xe       ⋯ Apple
3     512       NVMe         Dedicated  NVIDIA RTX 3060     ⋯ Lenovo
4    1000       HDD          Integrated Intel UHD           ⋯ Samsung
5    1000       HDD          Integrated Intel UHD           ⋯ Dell
6    2000       HDD          Dedicated  NVIDIA RTX 4080     ⋯ HP
7    4000       SSD          Dedicated  NVIDIA RTX 3060     ⋯ Dell
8     128       SSD          Dedicated  NVIDIA RTX 3060     ⋯ Lenovo
9    1000       SSD          Integrated Intel UHD           ⋯ HP
10    128       HDD          Integrated AMD Radeon Graphics ⋯ Custom Built
11   1000       HDD          Dedicated  AMD Radeon RX 7900  ⋯ MSI
12    512       SSD          Integrated Intel UHD           ⋯ Dell
13    512       SSD          Dedicated  NVIDIA RTX 3060     ⋯ MSI
14    512       HDD          Dedicated  NVIDIA RTX 4080     ⋯ Acer
15   1000       SSD          Dedicated  NVIDIA GTX 1650     ⋯ HP
16    512       HDD          Integrated Intel Iris Xe       ⋯ Dell
17   2000       NVMe         Dedicated  AMD Radeon RX 7900  ⋯ Dell
18    512       NVMe         Integrated Intel UHD           ⋯ HP
19    128       HDD          Integrated Intel UHD           ⋯ Samsung
20   2000       HDD          Integrated AMD Radeon Graphics ⋯ Apple
21    512       SSD          Integrated Intel Iris Xe       ⋯ Custom Built
22    512       HDD          Dedicated  NVIDIA GTX 1650     ⋯ Samsung
23   1000       SSD          Integrated Intel Iris Xe       ⋯ HP
24    512       NVMe         Integrated Intel UHD           ⋯ Samsung
25    128       SSD          None                           ⋯ Dell
26    512       NVMe         Integrated AMD Radeon Graphics ⋯ Dell
27   4000       SSD          Dedicated  AMD Radeon RX 6600  ⋯ ASUS
28   1000       HDD          Integrated Intel Iris Xe       ⋯ Lenovo
29   1000       NVMe         Integrated AMD Radeon Graphics ⋯ Lenovo
30   1000       SSD          Dedicated  NVIDIA RTX 3060     ⋯ Acer
⋮    ⋮          ⋮            ⋮          ⋮                   ⋱ ⋮
971  8000       SSD          Dedicated  NVIDIA GTX 1650     ⋯ Lenovo
972  1000       NVMe         Dedicated  NVIDIA GTX 1650     ⋯ MSI
973   512       SSD          Integrated Intel UHD           ⋯ Samsung
974  2000       NVMe         Dedicated  AMD Radeon RX 6600  ⋯ HP
975   512       HDD          Dedicated  NVIDIA GTX 1650     ⋯ ASUS
976  4000       SSD          Integrated Intel Iris Xe       ⋯ ASUS
977   512       HDD          Dedicated  NVIDIA RTX 3060     ⋯ Apple
978  1000       HDD          Dedicated  AMD Radeon RX 6600  ⋯ HP
979   128       HDD          Integrated Intel UHD           ⋯ MSI
980   512       HDD          Dedicated  NVIDIA RTX 4080     ⋯ HP
981  2000       SSHD         Integrated Intel Iris Xe       ⋯ Custom Built
982  2000       HDD          None                           ⋯ ASUS
983   256       SSD          Dedicated  NVIDIA GTX 1650     ⋯ Custom Built
984   256       NVMe         Integrated Intel Iris Xe       ⋯ HP
985  2000       SSD          Integrated Intel UHD           ⋯ Samsung
986  4000       HDD          Dedicated  AMD Radeon RX 6600  ⋯ Dell
987   128       NVMe         Integrated Intel UHD           ⋯ MSI
988   512       SSD          Integrated Intel UHD           ⋯ Lenovo
989   512       NVMe         Dedicated  AMD Radeon RX 7900  ⋯ Apple
990  4000       NVMe         Integrated AMD Radeon Graphics ⋯ HP
991   128       SSHD         Integrated Intel UHD           ⋯ Dell
992   256       SSD          Dedicated  NVIDIA RTX 3060     ⋯ Acer
993  2000       SSD          Dedicated  NVIDIA RTX 3060     ⋯ ASUS
994   128       SSD          Dedicated  NVIDIA RTX 3060     ⋯ Acer
995   512       HDD          Dedicated  AMD Radeon RX 6600  ⋯ HP
996   512       NVMe         Integrated Intel UHD           ⋯ HP
997   512       HDD          Integrated Intel UHD           ⋯ Samsung
998   512       SSD          Integrated AMD Radeon Graphics ⋯ MSI
999  1000       NVMe         Dedicated  NVIDIA GTX 1650     ⋯ Lenovo
1000  256       SSD          Dedicated  NVIDIA A6000        ⋯ Acer
     Model          Purchase_Date Age_Days Condition Price_USD
1    Inspiron 1409  2023-07-29     930     Good      1159
2    ZBook 5012     2023-09-14     883     Good      1616
3    EliteBook 3286 2025-06-06     252     Like New  2568
4    Inspiron 9935  2025-10-01     135     Like New  1619
5    Inspiron 7912  2024-09-08     523     New       1570
6    XPS 1488       2023-12-02     804     Good      2285
7    Inspiron 4582  2024-04-24     660     Good      2093
8    EliteBook 9279 2025-03-31      NA     Fair      2445
9    XPS 4257       2025-11-25      80     Fair      1156
10   Vostro 7873    2022-10-17    1215     Like New  1220
11   EliteBook 8359 2022-01-28    1477     Like New   793
12   ZBook 1106     2022-05-17    1368     New       2655
13   ThinkPad 7924  2023-03-27    1054     Like New  3690
14   MacBook 5552   2024-12-26     414     Poor       886
15   ThinkPad 4527  2025-02-10     368     New       1353
16   MacBook 2674   2023-05-13    1007     Poor      1647
17   Inspiron 7224  2023-05-27     993     Good      1373
18   Inspiron 6881  2024-06-27     596     Good      2586
19   MacBook 5333   2023-05-02    1018     New       1441
20   XPS 8527       2024-03-14     701     Good      1576
21   Vostro 3045    2023-04-05    1045     Good      6015
22   ROG 2291       2024-08-13     549     Like New  1089
23   Vostro 5803    2025-06-12     246     Like New  4868
24   MacBook 4150   2025-05-06     283     New       2360
25   Inspiron 1750  2024-06-09     614     Good      2028
26   EliteBook 5741 2023-07-28     931     Like New  1403
27   Inspiron 4814  2023-11-30     806     Good      2314
28   Inspiron 7227  2025-06-26     232     Good      5957
29   ZBook 8428     2025-04-03     316     Like New  1374
30   MacBook 3664   2023-10-29     838     Good      1615
⋮    ⋮              ⋮             ⋮        ⋮         ⋮
971  Vostro 6325    2024-01-31     744     Like New  2938
972  Predator 9609  2026-01-01      43     Good      1769
973  ROG 6140       2025-01-05     404     Good      1957
974  ThinkPad 8531  2024-06-18     605     Poor      1513
975  Vostro 6608    2024-04-28     656     Good      1056
976  Vostro 6804    2025-05-26     263     Good      2439
977  ZBook 8932     2025-12-05      70     Good      1612
978  EliteBook 5038 2024-04-23     661     Like New   896
979  ZBook 5890     2022-07-08    1316     Good      1494
980  EliteBook 5876 2022-09-24      NA     New       6716
981  ZBook 4396     2023-09-25     872     Good      1537
982  Predator 6194  2023-11-14     822     Good      2084
983  Predator 6714  2025-09-19     147     Fair      1112
984  Vostro 5480    2026-01-19      25     Good      1373
985  ZBook 2996     2022-06-07    1347     Fair      1529
986  Vostro 7220    2023-01-07    1133     New       7768
987  ROG 6654       2024-03-22     693     New       1199
988  ThinkPad 5758  2025-06-07     251     Good      1260
989  XPS 5712       2024-10-19     482     Good      1161
990  Inspiron 6674  2024-02-29     715     Good      3478
991  Predator 5201  2023-11-20     816     Good      1293
992  Predator 4505  2024-04-02     682     Like New  1484
993  EliteBook 9824 2025-08-22     175     Good      1452
994  ZBook 5450     2022-05-14    1371     New       1047
995  ThinkPad 2789  2022-11-07    1194     Like New  1200
996  EliteBook 4972 2026-02-11       2     New       2477
997  XPS 9700       2024-05-15     639     Good      2006
998  EliteBook 4814 2024-03-09     706     Good       710
999  XPS 2641       2025-02-16     362     Like New  1143
1000 ROG 6411       2022-07-04    1320     Good      2508
     Power_Consumption_W Weight_kg Screen_Size_inch Case_Type
1    238                  NA         NA             Full Tower
2    218                  NA         NA
3    393                 3.1       13.3
4    118                  NA       27.0
5    128                  NA         NA             Small Form Factor
6    324                  NA       16.0
7    296                  NA         NA             Full Tower
8    325                 1.0       14.0
9     84                 3.0       13.3
10    97                  NA         NA             Mini Tower
11   232                 1.9       15.6
12   219                  NA         NA             Full Tower
13   453                  NA         NA             Mid Tower
14   219                  NA         NA             Mid Tower
15   276                  NA         NA
16   151                 2.8       14.0
17   248                  NA         NA             Mid Tower
18   223                 1.9       14.0
19   133                  NA       15.6
20   112                  NA         NA             Mid Tower
21   607                  NA       24.0
22   241                 2.5       15.6
23   496                  NA         NA
24   219                  NA         NA             Full Tower
25   187                 2.6         NA
26    93                 2.0       17.3
27   332                 2.3       13.3
28   632                  NA         NA
29    88                  NA       14.0
30   302                  NA         NA             Mini Tower
⋮    ⋮                   ⋮         ⋮                ⋮
971  406                  NA         NA
972  278                 3.3       14.0
973  139                  NA         NA             Mini Tower
974  292                  NA       17.3
975  241                 2.0       16.0
976  312                  NA         NA
977  289                  NA         NA             Mid Tower
978  242                  NA         NA             Small Form Factor
979  143                 2.3       16.0
980  777                  NA         NA             Mini Tower
981  206                  NA         NA
982  138                  NA         NA             Mid Tower
983  265                 1.7       15.6
984  147                  NA         NA             Mid Tower
985  106                  NA         NA             Mini Tower
986  862                  NA         NA
987  105                  NA         NA             Mid Tower
988  101                 1.7       15.6
989  267                  NA         NA
990   NA                  NA         NA             Small Form Factor
991  209                  NA         NA
992  287                  NA         NA             Mini Tower
993  276                  NA         NA             Full Tower
994  237                  NA       14.0
995  259                  NA         NA             Full Tower
996  223                 1.1       24.0
997  183                  NA         NA             Mid Tower
998   73                 1.7       24.0
999  228                  NA         NA             Mini Tower
1000 451                  NA         NA

 [1] "ID"                  "CPU_Frequency_GHz"   "CPU_Cores"
 [4] "CPU_Brand"           "CPU_Generation"      "RAM_GB"
 [7] "Storage_GB"          "Storage_Type"        "GPU_Type"
[10] "GPU_Model"           "GPU_Memory_GB"       "WIFI"
[13] "WIFI_Standard"       "Bluetooth"           "Bluetooth_Version"
[16] "Computer_Type"       "Operating_System"    "USB_3_Ports"
[19] "USB_C_Ports"         "USB_2_Ports"         "Ethernet_Speed"
[22] "Brand"               "Model"               "Purchase_Date"
[25] "Age_Days"            "Condition"           "Price_USD"
[28] "Power_Consumption_W" "Weight_kg"           "Screen_Size_inch"
[31] "Case_Type"

Размер датасета: 1000 x 31

   Min. 1st Qu.  Median    Mean 3rd Qu.    Max.    NA's
  0.100   1.000   1.000   2.143   2.500  10.000      46

---
## 3. Фильтрация по требованиям криптовалютной биржи

In [ ]:
# Отбор по критериям варианта 5 (Криптовалютная биржа, HFT)
C <- Data$ID[
  (Data$CPU_Cores >= 16) &
  (Data$RAM_GB >= 64) &
  (Data$Storage_GB >= 1000) &
  (Data$Ethernet_Speed_Gbps  >= 2.5) &
  (Data$Price_USD <= 8000) &
  (Data$Storage_Type %in% c("SSD", "NVMe")) &
  (Data$Condition %in% c("Like New", "New")) &
  (!is.na(Data$Power_Consumption_W)) &
  (Data$Power_Consumption_W <= 800)
]

C

[1] "PC-0045" "PC-0075" "PC-0186" "PC-0231" "PC-0325" "PC-0956"

In [ ]:
# Убираем пропущенные значения
C <- C[!is.na(C)]
cat("Количество конфигураций, прошедших отбор:", length(C), "\n")
C

Количество конфигураций, прошедших отбор: 6

[1] "PC-0045" "PC-0075" "PC-0186" "PC-0231" "PC-0325" "PC-0956"

---
## 4. Формирование датафрейма для Парето-оптимизации

In [ ]:
F <- data.frame(
  Data$CPU_Cores[Data$ID %in% C],
  Data$RAM_GB[Data$ID %in% C],
  Data$Storage_GB[Data$ID %in% C],
  Data$Ethernet_Speed_Gbps[Data$ID %in% C],
  1 / Data$Price_USD[Data$ID %in% C],
  1 / Data$Power_Consumption_W[Data$ID %in% C]
)

colnames(F) <- c(
  "CPU_Cores",
  "RAM_GB",
  "Storage_GB",
  "Ethernet_Speed_Gbps",
  "Inv_Price_USD",
  "Inv_Power_W"
)

rownames(F) <- C

View(F)

        CPU_Cores RAM_GB Storage_GB Ethernet_Speed_Gbps Inv_Price_USD
PC-0045 16        256    2000        2.5                0.0003065604
PC-0075 32        256    1000        2.5                0.0002319647
PC-0186 24        512    1000        2.5                0.0001990050
PC-0231 16         64    1000        2.5                0.0004576659
PC-0325 32        128    2000       10.0                0.0002674512
PC-0956 24         64    4000        2.5                0.0003051572
        Inv_Power_W
PC-0045 0.002336449
PC-0075 0.002008032
PC-0186 0.002293578
PC-0231 0.005813953
PC-0325 0.002252252
PC-0956 0.004132231

---
## 5. Парето-оптимизация

In [ ]:
# Проверка: X доминирует по Парето Y (X >_p Y)
DPareto <- function(X, Y) {
  p <- TRUE
  l <- FALSE
  i <- 1
  while (p & (i <= length(X))) {
    if (X[i] < Y[i]) p <- FALSE
    if (X[i] > Y[i]) l <- TRUE
    i <- i + 1
  }
  if (!p | !l) return(FALSE)
  else return(TRUE)
}

result <- c()
for (i in c(1:length(rownames(F)))) {
  p <- TRUE
  for (j in c(1:length(rownames(F)))) {
    if (DPareto(F[j, ], F[i, ]))
      p <- FALSE
  }
  if (p) result <- c(result, rownames(F)[i])
}
cat("Парето-оптимальные конфигурации:", length(result), "\n")
result

Парето-оптимальные конфигурации: 6

[1] "PC-0045" "PC-0075" "PC-0186" "PC-0231" "PC-0325" "PC-0956"

In [ ]:
FF <- data.frame(
  Data$CPU_Cores[Data$ID %in% result],
  Data$RAM_GB[Data$ID %in% result],
  Data$Storage_GB[Data$ID %in% result],
  Data$Ethernet_Speed_Gbps[Data$ID %in% result],
  Data$Price_USD[Data$ID %in% result],
  Data$Power_Consumption_W[Data$ID %in% result]
)

colnames(FF) <- c(
  "CPU_Cores",
  "RAM_GB",
  "Storage_GB",
  "Ethernet_Speed_Gbps",
  "Price_USD",
  "Power_Consumption_W"
)

rownames(FF) <- result
FF

        CPU_Cores RAM_GB Storage_GB Ethernet_Speed_Gbps Price_USD
PC-0045 16        256    2000        2.5                3262
PC-0075 32        256    1000        2.5                4311
PC-0186 24        512    1000        2.5                5025
PC-0231 16         64    1000        2.5                2185
PC-0325 32        128    2000       10.0                3739
PC-0956 24         64    4000        2.5                3277
        Power_Consumption_W
PC-0045 428
PC-0075 498
PC-0186 436
PC-0231 172
PC-0325 444
PC-0956 242

---
## 6. Нормирование критериев

In [ ]:
# CPU
mmax <- max(FF$CPU_Cores)
mmin <- min(FF$CPU_Cores)
CPU_Cores_norm <- (FF$CPU_Cores - mmin) * 100 / (mmax - mmin)

# RAM
mmax <- max(FF$RAM_GB)
mmin <- min(FF$RAM_GB)
RAM_GB_norm <- (FF$RAM_GB - mmin) * 100 / (mmax - mmin)

# Storage
mmax <- max(FF$Storage_GB)
mmin <- min(FF$Storage_GB)
Storage_GB_norm <- (FF$Storage_GB - mmin) * 100 / (mmax - mmin)

# Network (чем больше — тем лучше)
mmax <- max(FF$Ethernet_Speed_Gbps)
mmin <- min(FF$Ethernet_Speed_Gbps)
Ethernet_Speed_Gbps_norm <- (FF$Ethernet_Speed_Gbps - mmin) * 100 / (mmax - mmin)

# Цена (чем меньше — тем лучше)
mmax <- max(FF$Price_USD)
mmin <- min(FF$Price_USD)
Price_USD_norm <- (mmax - FF$Price_USD) * 100 / (mmax - mmin)

# Энергопотребление (чем меньше — тем лучше)
mmax <- max(FF$Power_Consumption_W)
mmin <- min(FF$Power_Consumption_W)
Power_Consumption_W_norm <- (mmax - FF$Power_Consumption_W) * 100 / (mmax - mmin)

WW <- data.frame(
  CPU_Cores_norm,
  RAM_GB_norm,
  Storage_GB_norm,
  Ethernet_Speed_Gbps_norm,
  Price_USD_norm,
  Power_Consumption_W_norm
)

rownames(WW) <- rownames(FF)

View(WW)

        CPU_Cores_norm RAM_GB_norm Storage_GB_norm Ethernet_Speed_Gbps_norm
PC-0045   0             42.85714    33.33333         0
PC-0075 100             42.85714     0.00000         0
PC-0186  50            100.00000     0.00000         0
PC-0231   0              0.00000     0.00000         0
PC-0325 100             14.28571    33.33333       100
PC-0956  50              0.00000   100.00000         0
        Price_USD_norm Power_Consumption_W_norm
PC-0045  62.07746       21.47239
PC-0075  25.14085        0.00000
PC-0186   0.00000       19.01840
PC-0231 100.00000      100.00000
PC-0325  45.28169       16.56442
PC-0956  61.54930       78.52761

---
## 7. Идеальная точка и расстояние (евклидова метрика)

In [ ]:
ideal <- apply(WW, 2, max)
ideal

stopifnot(ncol(WW) == length(ideal))
summary(WW)

colnames(WW)

          CPU_Cores_norm              RAM_GB_norm          Storage_GB_norm
                     100                      100                      100
Ethernet_Speed_Gbps_norm           Price_USD_norm Power_Consumption_W_norm
                     100                      100                      100

 CPU_Cores_norm   RAM_GB_norm      Storage_GB_norm  Ethernet_Speed_Gbps_norm
 Min.   :  0.0   Min.   :  0.000   Min.   :  0.00   Min.   :  0.00
 1st Qu.: 12.5   1st Qu.:  3.571   1st Qu.:  0.00   1st Qu.:  0.00
 Median : 50.0   Median : 28.571   Median : 16.67   Median :  0.00
 Mean   : 50.0   Mean   : 33.333   Mean   : 27.78   Mean   : 16.67
 3rd Qu.: 87.5   3rd Qu.: 42.857   3rd Qu.: 33.33   3rd Qu.:  0.00
 Max.   :100.0   Max.   :100.000   Max.   :100.00   Max.   :100.00
 Price_USD_norm   Power_Consumption_W_norm
 Min.   :  0.00   Min.   :  0.00
 1st Qu.: 30.18   1st Qu.: 17.18
 Median : 53.42   Median : 20.25
 Mean   : 49.01   Mean   : 39.26
 3rd Qu.: 61.95   3rd Qu.: 64.26
 Max.   :100.00   Max.   :100.00

[1] "CPU_Cores_norm"           "RAM_GB_norm"
[3] "Storage_GB_norm"          "Ethernet_Speed_Gbps_norm"
[5] "Price_USD_norm"           "Power_Consumption_W_norm"

In [ ]:
distance <- function(A, B) {
  return(sqrt(sum((A - B)^2)))
}

distances <- sapply(result, function(i) distance(ideal, WW[i, ]))
names(distances) <- result
for (i in result) {
  print(paste(i, ":", as.character(distance(ideal, WW[i, ]))))
}

[1] "PC-0045 : 187.921404746074"
[1] "PC-0075 : 197.152730641042"
[1] "PC-0186 : 197.631016653886"
[1] "PC-0231 : 200"
[1] "PC-0325 : 147.468549645876"
[1] "PC-0956 : 156.331443737425"

In [ ]:
# Конфигурация, ближайшая к идеальной точке
best_id <- result[which.min(distances)]
best_distance <- min(distances)
cat("Рекомендуемая конфигурация (по расстоянию до идеальной точки):", best_id, "\n")
cat("Расстояние до идеальной точки:", round(best_distance, 4), "\n\n")
Data[Data$ID == best_id, ]

Рекомендуемая конфигурация (по расстоянию до идеальной точки): PC-0325
Расстояние до идеальной точки: 147.4685

    ID      CPU_Frequency_GHz CPU_Cores CPU_Brand     CPU_Generation RAM_GB
325 PC-0325 5.01              32        Intel Core i3 7              128
    Storage_GB Storage_Type GPU_Type  GPU_Model          ⋯ Model
325 2000       NVMe         Dedicated AMD Radeon RX 7900 ⋯ MacBook 3979
    Purchase_Date Age_Days Condition Price_USD Power_Consumption_W Weight_kg
325 2022-04-06    1409     Like New  3739      444                 NA
    Screen_Size_inch Case_Type Ethernet_Speed_Gbps
325 14                         10

---
## 8. Линейная свертка с приоритетами

In [ ]:
# Порядок критериев: CPU, RAM, Storage, Network, Price, Power

a <- c(3, 3, 2, 3, 2, 3)
anorm <- a / sum(a)

cat("Нормированные веса критериев:\n")
print(anorm)
cat("Сумма весов:", sum(anorm), "\n\n")

stopifnot(length(a) == ncol(WW))

scores <- sapply(result, function(i) sum(anorm * WW[i, ]))
names(scores) <- result

cat("Значения линейной свёртки для Парето-оптимальных альтернатив:\n")
for (i in result) {
  cat(i, ":", round(scores[i], 4), "\n")
}

scores <- sort(scores, decreasing = TRUE)

cat("\nОтсортированные оценки:\n")
print(round(scores, 4))

Нормированные веса критериев:
[1] 0.1875 0.1875 0.1250 0.1875 0.1250 0.1875
Сумма весов: 1

Значения линейной свёртки для Парето-оптимальных альтернатив:
PC-0045 : 23.9881
PC-0075 : 29.9283
PC-0186 : 31.691
PC-0231 : 31.25
PC-0325 : 53.1113
PC-0956 : 44.2926

Отсортированные оценки:
PC-0325 PC-0956 PC-0186 PC-0231 PC-0075 PC-0045
53.1113 44.2926 31.6910 31.2500 29.9283 23.9881

In [ ]:
# Лучшая конфигурация по линейной свёртке
best_weighted_id <- names(scores)[which.max(scores)]
best_weighted_score <- max(scores)

cat("\nРекомендуемая конфигурация (по линейной свёртке):", best_weighted_id, "\n")
cat("Счёт:", round(best_weighted_score, 4), "\n\n")

Data[Data$ID == best_weighted_id, ]

Рекомендуемая конфигурация (по линейной свёртке): PC-0325
Счёт: 53.1113

    ID      CPU_Frequency_GHz CPU_Cores CPU_Brand     CPU_Generation RAM_GB
325 PC-0325 5.01              32        Intel Core i3 7              128
    Storage_GB Storage_Type GPU_Type  GPU_Model          ⋯ Model
325 2000       NVMe         Dedicated AMD Radeon RX 7900 ⋯ MacBook 3979
    Purchase_Date Age_Days Condition Price_USD Power_Consumption_W Weight_kg
325 2022-04-06    1409     Like New  3739      444                 NA
    Screen_Size_inch Case_Type Ethernet_Speed_Gbps
325 14                         10

---
# **ЧАСТЬ 2. МАСШТАБИРОВАНИЕ ИНФРАСТРУКТУРЫ**
---

## 9. Постановка задачи (Часть 2)

Во второй части рассматривается задача **двухуровневой оптимизации** инфраструктуры криптовалютной биржи (**HFT**).

Инфраструктура разбивается на три сегмента:

1. **Trading** — узлы обработки ордеров и matching engine, критична минимальная задержка.
2. **Gateways** — прием и маршрутизация сетевого трафика, важна высокая пропускная способность.
3. **DB** — хранение состояния, журналирование и доступ к данным, приоритетны RAM и Storage.

На **нижнем уровне** для каждого сегмента формируется критерий эффективности на основе нормированных характеристик серверов.

На **верхнем уровне** выполняется выбор количества серверов по сегментам с учетом ограничений по:
- числу узлов;
- стоимости инфраструктуры;
- допустимому составу сегментов.

Оптимизация проводится в два этапа:
1. сначала максимизируется интегральная эффективность инфраструктуры;
2. затем методом последовательных уступок минимизируется стоимость при допустимом снижении эффективности.

In [ ]:
# ========================================
# 1. Отбор допустимых альтернатив
# ========================================

# Оставляем серверы, удовлетворяющие минимальным требованиям
C <- Data$ID[Data$CPU_Cores >= 8 & Data$RAM_GB >= 32]
C <- na.omit(C)

cat("Количество альтернатив после первичного отбора:", length(C), "\n")


# ========================================
# 2. Формирование матрицы критериев для Парето-анализа
# ========================================

F <- data.frame(
  CPU_Frequency_GHz = Data$CPU_Frequency_GHz[Data$ID %in% C],
  CPU_Cores         = Data$CPU_Cores[Data$ID %in% C],
  RAM_GB            = Data$RAM_GB[Data$ID %in% C],
  Storage_GB        = Data$Storage_GB[Data$ID %in% C],
  Price_USD         = 1 / Data$Price_USD[Data$ID %in% C]
)

rownames(F) <- Data$ID[Data$ID %in% C]
F <- na.omit(F)

cat("Размерность матрицы критериев F:\n")
print(dim(F))
print(head(F))


# ========================================
# 3. Поиск Парето-оптимальных альтернатив
# ========================================

result <- c()

for (i in 1:nrow(F)) {
  p <- TRUE

  for (j in 1:nrow(F)) {
    if (i != j) {
      if (DPareto(F[j, ], F[i, ])) {
        p <- FALSE
        break
      }
    }
  }

  if (p) {
    result <- c(result, rownames(F)[i])
  }
}

cat("\nПарето-оптимальные альтернативы:\n")
print(result)
cat("Количество Парето-оптимальных альтернатив:", length(result), "\n")


# ========================================
# 4. Формирование таблицы Парето-оптимальных конфигураций
# ========================================

FF <- data.frame(
  CPU_Frequency_GHz = Data$CPU_Frequency_GHz[Data$ID %in% result],
  CPU_Cores         = Data$CPU_Cores[Data$ID %in% result],
  RAM_GB            = Data$RAM_GB[Data$ID %in% result],
  Storage_GB        = Data$Storage_GB[Data$ID %in% result],
  Price_USD         = Data$Price_USD[Data$ID %in% result]
)

rownames(FF) <- result

cat("\nТаблица Парето-оптимальных альтернатив FF:\n")
print(FF)


# ========================================
# 5. Нормирование критериев
# ========================================

normalize_benefit_100 <- function(x) {
  if (max(x) == min(x)) {
    return(rep(100, length(x)))
  }
  (x - min(x)) * 100 / (max(x) - min(x))
}

normalize_cost_100 <- function(x) {
  if (max(x) == min(x)) {
    return(rep(100, length(x)))
  }
  (max(x) - x) * 100 / (max(x) - min(x))
}

CPU_Cores_norm         <- normalize_benefit_100(FF$CPU_Cores)
CPU_Frequency_GHz_norm <- normalize_benefit_100(FF$CPU_Frequency_GHz)
RAM_GB_norm            <- normalize_benefit_100(FF$RAM_GB)
Storage_GB_norm        <- normalize_benefit_100(FF$Storage_GB)
Price_USD_norm         <- normalize_cost_100(FF$Price_USD)


# ========================================
# 6. Формирование нормированной таблицы
# ========================================

WW <- data.frame(
  CPU_Cores_norm,
  CPU_Frequency_GHz_norm,
  RAM_GB_norm,
  Storage_GB_norm,
  Price_USD_norm
)

rownames(WW) <- rownames(FF)

cat("\nНормированная таблица критериев WW:\n")
print(WW)

cat("\nКоличество альтернатив в WW:", nrow(WW), "\n")

Количество альтернатив после первичного отбора: 329
Размерность матрицы критериев F:
[1] 322   5
        CPU_Frequency_GHz CPU_Cores RAM_GB Storage_GB    Price_USD
PC-0003              4.10        12    256        512 0.0003894081
PC-0006              1.74         8    128       2000 0.0004376368
PC-0007              1.34         8     32       4000 0.0004777831
PC-0008              4.65        12    128        128 0.0004089980
PC-0013              4.51        24    256        512 0.0002710027
PC-0015              1.85        10     32       1000 0.0007390983

Парето-оптимальные альтернативы:
  [1] "PC-0003" "PC-0013" "PC-0015" "PC-0021" "PC-0025" "PC-0028" "PC-0030"
  [8] "PC-0041" "PC-0046" "PC-0051" "PC-0054" "PC-0055" "PC-0063" "PC-0075"
 [15] "PC-0080" "PC-0085" "PC-0089" "PC-0092" "PC-0099" "PC-0102" "PC-0104"
 [22] "PC-0105" "PC-0108" "PC-0115" "PC-0121" "PC-0122" "PC-0123" "PC-0125"
 [29] "PC-0135" "PC-0141" "PC-0153" "PC-0154" "PC-0159" "PC-0161" "PC-0166"
 [36] "PC-0167" "PC-0171" "PC-0176" "PC-0179" "PC-0180" "PC-0190" "PC-0192"
 [43] "PC-0198" "PC-0210" "PC-0221" "PC-0231" "PC-0241" "PC-0244" "PC-0249"
 [50] "PC-0255" "PC-0262" "PC-0278" "PC-0294" "PC-0302" "PC-0305" "PC-0312"
 [57] "PC-0314" "PC-0318" "PC-0323" "PC-0325" "PC-0336" "PC-0344" "PC-0345"
 [64] "PC-0349" "PC-0351" "PC-0352" "PC-0365" "PC-0368" "PC-0383" "PC-0387"
 [71] "PC-0389" "PC-0400" "PC-0407" "PC-0410" "PC-0415" "PC-0420" "PC-0426"
 [78] "PC-0428" "PC-0430" "PC-0432" "PC-0443" "PC-0445" "PC-0453" "PC-0458"
 [85] "PC-0462" "PC-0465" "PC-0469" "PC-0470" "PC-0472" "PC-0473" "PC-0476"
 [92] "PC-0478" "PC-0495" "PC-0500" "PC-0501" "PC-0507" "PC-0509" "PC-0513"
 [99] "PC-0518" "PC-0532" "PC-0540" "PC-0541" "PC-0553" "PC-0554" "PC-0560"
[106] "PC-0565" "PC-0569" "PC-0574" "PC-0578" "PC-0580" "PC-0585" "PC-0590"
[113] "PC-0611" "PC-0617" "PC-0619" "PC-0623" "PC-0624" "PC-0628" "PC-0631"
[120] "PC-0635" "PC-0639" "PC-0643" "PC-0646" "PC-0650" "PC-0665" "PC-0668"
[127] "PC-0672" "PC-0673" "PC-0675" "PC-0680" "PC-0682" "PC-0684" "PC-0689"
[134] "PC-0692" "PC-0699" "PC-0700" "PC-0701" "PC-0718" "PC-0719" "PC-0725"
[141] "PC-0730" "PC-0732" "PC-0736" "PC-0741" "PC-0751" "PC-0755" "PC-0757"
[148] "PC-0767" "PC-0773" "PC-0774" "PC-0775" "PC-0782" "PC-0784" "PC-0785"
[155] "PC-0787" "PC-0790" "PC-0801" "PC-0802" "PC-0806" "PC-0812" "PC-0816"
[162] "PC-0823" "PC-0829" "PC-0836" "PC-0839" "PC-0844" "PC-0849" "PC-0854"
[169] "PC-0861" "PC-0866" "PC-0871" "PC-0876" "PC-0882" "PC-0893" "PC-0907"
[176] "PC-0917" "PC-0918" "PC-0925" "PC-0932" "PC-0945" "PC-0955" "PC-0956"
[183] "PC-0957" "PC-0974" "PC-0979" "PC-0993"
Количество Парето-оптимальных альтернатив: 186

Таблица Парето-оптимальных альтернатив FF:
        CPU_Frequency_GHz CPU_Cores RAM_GB Storage_GB Price_USD
PC-0003              4.10        12    256        512      2568
PC-0013              4.51        24    256        512      3690
PC-0015              1.85        10     32       1000      1353
PC-0021              3.61         8   1024        512      6015
PC-0025              2.97        24     32        128      2028
PC-0028              3.21        12   1024       1000      5957
PC-0030              1.29        12     64       1000      1615
PC-0041              1.60         8    256        256      2037
PC-0046              3.82         8     64       2000      1764
PC-0051              5.08        12     32        256      1735
PC-0054              4.77        10    512        512      3670
PC-0055              3.55        64    128       1000      5593
PC-0063              4.50        10    128       1000      2320
PC-0075              4.00        32    256       1000      4311
PC-0080              1.58        24    128       4000      2973
PC-0085              2.38        24     32       2000      2147
PC-0089              4.74        64    128       1000      5734
PC-0092              4.02         8   1024       8000      7977
PC-0099              1.20        10    128        128      1501
PC-0102              3.71        32     32       2000      3362
PC-0104              3.19        16     64        512      1757
PC-0105              4.82        64    128        512      4454
PC-0108              4.20        10    256        128      2490
PC-0115              3.70         8     64        256      1379
PC-0121              4.41        16    128        512      2268
PC-0122              4.77        24     32        256      2433
PC-0123              2.40        12   1024        128      5805
PC-0125              2.03         8   1024       2000      6072
PC-0135              4.97         8     64        256      1479
PC-0141              5.05        12    128        512      2394
PC-0153              1.69         8     64       2000      1499
PC-0154              3.11         8    128        512      1760
PC-0159              2.07        12     32       2000      1783
PC-0161              2.61        12     64        512      1494
PC-0166              4.52        12   1024        512      6020
PC-0167              2.42        12     64       4000      2151
PC-0171              3.88         8     64       1000      1542
PC-0176              1.81         8    128        256      1486
PC-0179              4.94        10     64       2000      2148
PC-0180              1.66         8     32       1000      1193
PC-0190              2.09        10     64       2000      1956
PC-0192              4.78         8    256       4000      3198
PC-0198              4.78        32    256       4000      4792
PC-0210              1.76        64    256       1000      5067
PC-0221              3.80        24     64       1000      2831
PC-0231              4.36        16     64       1000      2185
PC-0241              4.96        12    128        512      1993
PC-0244              2.62        12   2048       1000     13265
PC-0249              5.05        16     32       4000      2995
PC-0255              1.79         8    256        512      2147
PC-0262              5.16        10     64       1000      2130
PC-0278              3.76        32     32        512      3038
PC-0294              2.58         8     32       1000      1330
PC-0302              3.28        24     32       8000      3795
PC-0305              4.08        10    512        256      3505
PC-0312              1.42        16    256       1000      2782
PC-0314              5.05        12     64        128      2049
PC-0318              1.81        10     32        128      1068
PC-0323              3.81        12     64       2000      2206
PC-0325              5.01        32    128       2000      3739
PC-0336              1.27         8     32       2000      1423
PC-0344              2.88        10     32        256      1242
PC-0345              2.73        10    512        512      3413
PC-0349              2.64        32     32        512      2346
PC-0351              3.16        12     64        256      1511
PC-0352              4.61         8    256        512      2361
PC-0365              4.96        10     32       4000      2159
PC-0368              4.81        16     32        512      2079
PC-0383              3.68        32    256        128      3839
PC-0387              2.26        10     32        256      1208
PC-0389              4.18        32     64        128      3217
PC-0400              4.19        10     64       1000      1699
PC-0407              2.70        12     32       4000      2383
PC-0410              1.47        12     32        128      1204
PC-0415              3.69         8     32       2000      1570
PC-0420              4.18        24     32        128      2059
PC-0426              3.35        32    256       1000      4270
PC-0428              4.74        24    512       1000      4329
PC-0430              1.58        12    256       1000      2519
PC-0432              4.22         8    128       8000      3072
PC-0443              2.63         8    128        256      1553
PC-0445              4.43        12     32       8000      3245
PC-0453              2.84        12     32       1000      1625
PC-0458              3.02         8     64       1000      1483
PC-0462              3.76         8    256        256      2290
PC-0465              5.04        64     64        256      4161
PC-0469              2.02        12     32       2000      1639
PC-0470              5.05        10     32        256      1424
PC-0472              5.08        10   1024       2000      7601
PC-0473              1.28        12    256       1000      2456
PC-0476              5.17         8    256       2000      2759
PC-0478              3.37        10    128       1000      1831
PC-0495              3.00         8     32       1000      1465
PC-0500              5.14        12     32       2000      1846
PC-0501              3.96         8    128        512      1987
PC-0507              4.83         8    256       8000      4087
PC-0509              4.99         8    128       2000      2316
PC-0513              4.92        24     32       8000      4253
PC-0518              4.42        16     32        512      1778
PC-0532              5.20         8    128       2000      2739
PC-0540              1.63         8    128        128      1449
PC-0541              5.01        10     64        256      1552
PC-0553              3.36        12    128       1000      1963
PC-0554              3.40        16    512       1000      4224
PC-0560              3.64        16     32        512      1588
PC-0565              2.54        12     32        512      1332
PC-0569              4.81         8    128       2000      2314
PC-0574              3.65        12     32       8000      3214
PC-0578              4.90         8     64        512      1808
PC-0580              2.16         8     64        512      1240
PC-0585              3.70        32     32        512      2551
PC-0590              1.72        10     64        256      1257
PC-0611              1.26        16    128       1000      1885
PC-0617              1.35        64     32       1000      4372
PC-0619              4.41         8    128       2000      2139
PC-0623              2.62         8     32        256      1122
PC-0624              3.09        24    256       4000      4387
PC-0628              4.16         8     64       4000      2411
PC-0631              4.02        10     64       2000      1975
PC-0635              1.54        16     64        128      1604
PC-0639              2.20        64    512        512      7538
PC-0643              1.97         8    128        512      1666
PC-0646              4.75        10     32        256      1382
PC-0650              3.14        10     32       8000      2674
PC-0665              1.52        64     64       1000      4744
PC-0668              1.76        24     64        256      2254
PC-0672              4.78        12     32        128      1613
PC-0673              1.43        12     64       2000      1935
PC-0675              2.78        10    256       1000      2698
PC-0680              4.65         8     32        512      1328
PC-0682              2.16        32    128        256      2799
PC-0684              3.84        12     32        256      1429
PC-0689              4.25         8     32        128      1293
PC-0692              2.84         8     32       1000      1386
PC-0699              1.73        32    128       4000      4108
PC-0700              3.07         8    128        512      1721
PC-0701              3.28        32     32       1000      2659
PC-0718              5.06         8   1024        128      6865
PC-0719              1.61        32    128        512      3274
PC-0725              3.46         8     32        512      1207
PC-0730              1.77         8     32       1000      1219
PC-0732              4.44         8     32       8000      3367
PC-0736              4.70        16    128        512      2748
PC-0741              3.00        12     32       4000      2593
PC-0751              1.58         8     32       4000      1961
PC-0755              1.67        32    256        512      4082
PC-0757              3.64        24     32        256      2368
PC-0767              4.23        10     32       1000      1760
PC-0773              1.62        16    128        512      2205
PC-0774              2.73        24     32       2000      2640
PC-0775              4.37        10     32       1000      1790
PC-0782              3.33        16    128        512      2242
PC-0784              2.52         8    128       2000      1861
PC-0785              1.84         8    256       2000      2667
PC-0787              3.49         8   1024       1000      6338
PC-0790              4.98         8   2048       8000     13026
PC-0801              4.00        24    128        512      2760
PC-0802              1.73        10    256       4000      2788
PC-0806              4.12        10   1024       8000      8962
PC-0812              4.54        10     64        512      1588
PC-0816              3.23        32    128       1000      3433
PC-0823              2.47         8     64       2000      1610
PC-0829              4.12        10     32       2000      1802
PC-0836              2.82         8    256        512      2180
PC-0839              3.48        16    128       4000      3288
PC-0844              5.04         8    512        512      4465
PC-0849              3.16        16     32       2000      1917
PC-0854              4.78        12    256       4000      3306
PC-0861              4.28        10    256       2000      2938
PC-0866              3.39        24     32        512      2469
PC-0871              2.63        12    256        512      2397
PC-0876              1.74         8     32        512      1187
PC-0882              3.85        12    256       2000      2749
PC-0893              4.50        12    128       1000      2351
PC-0907              4.45        24   1024       1000      6693
PC-0917              2.31        16     64       2000      2348
PC-0918              4.99         8    128        512      2223
PC-0925              2.84        10     32       8000      2575
PC-0932              4.52         8     64        256      1434
PC-0945              1.95        10    128        256      1612
PC-0955              2.82        64    512        256      6903
PC-0956              2.67        24     64       4000      3277
PC-0957              3.23         8     64       4000      1981
PC-0974              1.98         8     64       2000      1513
PC-0979              3.14        12     64        128      1494
PC-0993              2.22         8     32       2000      1452

Нормированная таблица критериев WW:
        CPU_Cores_norm CPU_Frequency_GHz_norm RAM_GB_norm Storage_GB_norm
PC-0003       7.142857                  72.50   11.111111        4.878049
PC-0013      28.571429                  82.75   11.111111        4.878049
PC-0015       3.571429                  16.25    0.000000       11.077236
PC-0021       0.000000                  60.25   49.206349        4.878049
PC-0025      28.571429                  44.25    0.000000        0.000000
PC-0028       7.142857                  50.25   49.206349       11.077236
PC-0030       7.142857                   2.25    1.587302       11.077236
PC-0041       0.000000                  10.00   11.111111        1.626016
PC-0046       0.000000                  65.50    1.587302       23.780488
PC-0051       7.142857                  97.00    0.000000        1.626016
PC-0054       3.571429                  89.25   23.809524        4.878049
PC-0055     100.000000                  58.75    4.761905       11.077236
PC-0063       3.571429                  82.50    4.761905       11.077236
PC-0075      42.857143                  70.00   11.111111       11.077236
PC-0080      28.571429                   9.50    4.761905       49.186992
PC-0085      28.571429                  29.50    0.000000       23.780488
PC-0089     100.000000                  88.50    4.761905       11.077236
PC-0092       0.000000                  70.50   49.206349      100.000000
PC-0099       3.571429                   0.00    4.761905        0.000000
PC-0102      42.857143                  62.75    0.000000       23.780488
PC-0104      14.285714                  49.75    1.587302        4.878049
PC-0105     100.000000                  90.50    4.761905        4.878049
PC-0108       3.571429                  75.00   11.111111        0.000000
PC-0115       0.000000                  62.50    1.587302        1.626016
PC-0121      14.285714                  80.25    4.761905        4.878049
PC-0122      28.571429                  89.25    0.000000        1.626016
PC-0123       7.142857                  30.00   49.206349        0.000000
PC-0125       0.000000                  20.75   49.206349       23.780488
PC-0135       0.000000                  94.25    1.587302        1.626016
PC-0141       7.142857                  96.25    4.761905        4.878049
PC-0153       0.000000                  12.25    1.587302       23.780488
PC-0154       0.000000                  47.75    4.761905        4.878049
PC-0159       7.142857                  21.75    0.000000       23.780488
PC-0161       7.142857                  35.25    1.587302        4.878049
PC-0166       7.142857                  83.00   49.206349        4.878049
PC-0167       7.142857                  30.50    1.587302       49.186992
PC-0171       0.000000                  67.00    1.587302       11.077236
PC-0176       0.000000                  15.25    4.761905        1.626016
PC-0179       3.571429                  93.50    1.587302       23.780488
PC-0180       0.000000                  11.50    0.000000       11.077236
PC-0190       3.571429                  22.25    1.587302       23.780488
PC-0192       0.000000                  89.50   11.111111       49.186992
PC-0198      42.857143                  89.50   11.111111       49.186992
PC-0210     100.000000                  14.00   11.111111       11.077236
PC-0221      28.571429                  65.00    1.587302       11.077236
PC-0231      14.285714                  79.00    1.587302       11.077236
PC-0241       7.142857                  94.00    4.761905        4.878049
PC-0244       7.142857                  35.50  100.000000       11.077236
PC-0249      14.285714                  96.25    0.000000       49.186992
PC-0255       0.000000                  14.75   11.111111        4.878049
PC-0262       3.571429                  99.00    1.587302       11.077236
PC-0278      42.857143                  64.00    0.000000        4.878049
PC-0294       0.000000                  34.50    0.000000       11.077236
PC-0302      28.571429                  52.00    0.000000      100.000000
PC-0305       3.571429                  72.00   23.809524        1.626016
PC-0312      14.285714                   5.50   11.111111       11.077236
PC-0314       7.142857                  96.25    1.587302        0.000000
PC-0318       3.571429                  15.25    0.000000        0.000000
PC-0323       7.142857                  65.25    1.587302       23.780488
PC-0325      42.857143                  95.25    4.761905       23.780488
PC-0336       0.000000                   1.75    0.000000       23.780488
PC-0344       3.571429                  42.00    0.000000        1.626016
PC-0345       3.571429                  38.25   23.809524        4.878049
PC-0349      42.857143                  36.00    0.000000        4.878049
PC-0351       7.142857                  49.00    1.587302        1.626016
PC-0352       0.000000                  85.25   11.111111        4.878049
PC-0365       3.571429                  94.00    0.000000       49.186992
PC-0368      14.285714                  90.25    0.000000        4.878049
PC-0383      42.857143                  62.00   11.111111        0.000000
PC-0387       3.571429                  26.50    0.000000        1.626016

In [ ]:
WW

        CPU_Cores_norm CPU_Frequency_GHz_norm RAM_GB_norm Storage_GB_norm
PC-0003   7.142857     72.50                  11.111111     4.878049
PC-0013  28.571429     82.75                  11.111111     4.878049
PC-0015   3.571429     16.25                   0.000000    11.077236
PC-0021   0.000000     60.25                  49.206349     4.878049
PC-0025  28.571429     44.25                   0.000000     0.000000
PC-0028   7.142857     50.25                  49.206349    11.077236
PC-0030   7.142857      2.25                   1.587302    11.077236
PC-0041   0.000000     10.00                  11.111111     1.626016
PC-0046   0.000000     65.50                   1.587302    23.780488
PC-0051   7.142857     97.00                   0.000000     1.626016
PC-0054   3.571429     89.25                  23.809524     4.878049
PC-0055 100.000000     58.75                   4.761905    11.077236
PC-0063   3.571429     82.50                   4.761905    11.077236
PC-0075  42.857143     70.00                  11.111111    11.077236
PC-0080  28.571429      9.50                   4.761905    49.186992
PC-0085  28.571429     29.50                   0.000000    23.780488
PC-0089 100.000000     88.50                   4.761905    11.077236
PC-0092   0.000000     70.50                  49.206349   100.000000
PC-0099   3.571429      0.00                   4.761905     0.000000
PC-0102  42.857143     62.75                   0.000000    23.780488
PC-0104  14.285714     49.75                   1.587302     4.878049
PC-0105 100.000000     90.50                   4.761905     4.878049
PC-0108   3.571429     75.00                  11.111111     0.000000
PC-0115   0.000000     62.50                   1.587302     1.626016
PC-0121  14.285714     80.25                   4.761905     4.878049
PC-0122  28.571429     89.25                   0.000000     1.626016
PC-0123   7.142857     30.00                  49.206349     0.000000
PC-0125   0.000000     20.75                  49.206349    23.780488
PC-0135   0.000000     94.25                   1.587302     1.626016
PC-0141   7.142857     96.25                   4.761905     4.878049
⋮       ⋮              ⋮                      ⋮           ⋮
PC-0801  28.571429     70.00                   4.761905     4.878049
PC-0802   3.571429     13.25                  11.111111    49.186992
PC-0806   3.571429     73.00                  49.206349   100.000000
PC-0812   3.571429     83.50                   1.587302     4.878049
PC-0816  42.857143     50.75                   4.761905    11.077236
PC-0823   0.000000     31.75                   1.587302    23.780488
PC-0829   3.571429     73.00                   0.000000    23.780488
PC-0836   0.000000     40.50                  11.111111     4.878049
PC-0839  14.285714     57.00                   4.761905    49.186992
PC-0844   0.000000     96.00                  23.809524     4.878049
PC-0849  14.285714     49.00                   0.000000    23.780488
PC-0854   7.142857     89.50                  11.111111    49.186992
PC-0861   3.571429     77.00                  11.111111    23.780488
PC-0866  28.571429     54.75                   0.000000     4.878049
PC-0871   7.142857     35.75                  11.111111     4.878049
PC-0876   0.000000     13.50                   0.000000     4.878049
PC-0882   7.142857     66.25                  11.111111    23.780488
PC-0893   7.142857     82.50                   4.761905    11.077236
PC-0907  28.571429     81.25                  49.206349    11.077236
PC-0917  14.285714     27.75                   1.587302    23.780488
PC-0918   0.000000     94.75                   4.761905     4.878049
PC-0925   3.571429     41.00                   0.000000   100.000000
PC-0932   0.000000     83.00                   1.587302     1.626016
PC-0945   3.571429     18.75                   4.761905     1.626016
PC-0955 100.000000     40.50                  23.809524     1.626016
PC-0956  28.571429     36.75                   1.587302    49.186992
PC-0957   0.000000     50.75                   1.587302    49.186992
PC-0974   0.000000     19.50                   1.587302    23.780488
PC-0979   7.142857     48.50                   1.587302     0.000000
PC-0993   0.000000     25.50                   0.000000    23.780488
        Price_USD_norm
PC-0003 87.70189
PC-0013 78.50291
PC-0015 97.66336
PC-0021 59.44085
PC-0025 92.12921
PC-0028 59.91637
PC-0030 95.51529
PC-0041 92.05542
PC-0046 94.29368
PC-0051 94.53144
PC-0054 78.66689
PC-0055 62.90071
PC-0063 89.73518
PC-0075 73.41149
PC-0080 84.38141
PC-0085 91.15356
PC-0089 61.74469
PC-0092 43.35492
PC-0099 96.44995
PC-0102 81.19210
PC-0104 94.35107
PC-0105 72.23908
PC-0108 88.34140
PC-0115 97.45019
PC-0121 90.16152
PC-0122 88.80872
PC-0123 61.16258
PC-0125 58.97352
PC-0135 96.63032
PC-0141 89.12847
⋮       ⋮
PC-0801 86.12774
PC-0802 85.89817
PC-0806 35.27917
PC-0812 95.73666
PC-0816 80.60999
PC-0823 95.55628
PC-0829 93.98213
PC-0836 90.88300
PC-0839 81.79880
PC-0844 72.14889
PC-0849 93.03927
PC-0854 81.65123
PC-0861 84.66836
PC-0866 88.51357
PC-0871 89.10388
PC-0876 99.02435
PC-0882 86.21792
PC-0893 89.48102
PC-0907 53.88210
PC-0917 89.50562
PC-0918 90.53046
PC-0925 87.64450
PC-0932 96.99926
PC-0945 95.53989
PC-0955 52.16037
PC-0956 81.88899
PC-0957 92.51455
PC-0974 96.35156
PC-0979 96.50734
PC-0993 96.85168

In [ ]:
FF

        CPU_Frequency_GHz CPU_Cores RAM_GB Storage_GB Price_USD
PC-0003 4.10              12         256    512       2568
PC-0013 4.51              24         256    512       3690
PC-0015 1.85              10          32   1000       1353
PC-0021 3.61               8        1024    512       6015
PC-0025 2.97              24          32    128       2028
PC-0028 3.21              12        1024   1000       5957
PC-0030 1.29              12          64   1000       1615
PC-0041 1.60               8         256    256       2037
PC-0046 3.82               8          64   2000       1764
PC-0051 5.08              12          32    256       1735
PC-0054 4.77              10         512    512       3670
PC-0055 3.55              64         128   1000       5593
PC-0063 4.50              10         128   1000       2320
PC-0075 4.00              32         256   1000       4311
PC-0080 1.58              24         128   4000       2973
PC-0085 2.38              24          32   2000       2147
PC-0089 4.74              64         128   1000       5734
PC-0092 4.02               8        1024   8000       7977
PC-0099 1.20              10         128    128       1501
PC-0102 3.71              32          32   2000       3362
PC-0104 3.19              16          64    512       1757
PC-0105 4.82              64         128    512       4454
PC-0108 4.20              10         256    128       2490
PC-0115 3.70               8          64    256       1379
PC-0121 4.41              16         128    512       2268
PC-0122 4.77              24          32    256       2433
PC-0123 2.40              12        1024    128       5805
PC-0125 2.03               8        1024   2000       6072
PC-0135 4.97               8          64    256       1479
PC-0141 5.05              12         128    512       2394
⋮       ⋮                 ⋮         ⋮      ⋮          ⋮
PC-0801 4.00              24         128    512       2760
PC-0802 1.73              10         256   4000       2788
PC-0806 4.12              10        1024   8000       8962
PC-0812 4.54              10          64    512       1588
PC-0816 3.23              32         128   1000       3433
PC-0823 2.47               8          64   2000       1610
PC-0829 4.12              10          32   2000       1802
PC-0836 2.82               8         256    512       2180
PC-0839 3.48              16         128   4000       3288
PC-0844 5.04               8         512    512       4465
PC-0849 3.16              16          32   2000       1917
PC-0854 4.78              12         256   4000       3306
PC-0861 4.28              10         256   2000       2938
PC-0866 3.39              24          32    512       2469
PC-0871 2.63              12         256    512       2397
PC-0876 1.74               8          32    512       1187
PC-0882 3.85              12         256   2000       2749
PC-0893 4.50              12         128   1000       2351
PC-0907 4.45              24        1024   1000       6693
PC-0917 2.31              16          64   2000       2348
PC-0918 4.99               8         128    512       2223
PC-0925 2.84              10          32   8000       2575
PC-0932 4.52               8          64    256       1434
PC-0945 1.95              10         128    256       1612
PC-0955 2.82              64         512    256       6903
PC-0956 2.67              24          64   4000       3277
PC-0957 3.23               8          64   4000       1981
PC-0974 1.98               8          64   2000       1513
PC-0979 3.14              12          64    128       1494
PC-0993 2.22               8          32   2000       1452

In [ ]:
# ========================================
# Формирование весов сегментов и коэффициентов целевых функций
# ========================================

# 1. Относительные доли ресурсов по сегментам
cpu <- c(
  Trading  = (16 + 24) / 2,
  Gateways = (16 + 24) / 2,
  DB       = (24 + 32) / 2
)
a <- cpu / sum(cpu)

cat("Доли CPU по сегментам:\n")
print(a)


ram <- c(
  Trading  = (64 + 128) / 2,
  Gateways = (64 + 128) / 2,
  DB       = (128 + 256) / 2
)
b <- ram / sum(ram)

cat("\nДоли RAM по сегментам:\n")
print(b)


storage <- c(
  Trading  = (500 + 1000) / 2,
  Gateways = (500 + 1000) / 2,
  DB       = (2000 + 4000) / 2
)
c_share <- storage / sum(storage)

cat("\nДоли Storage по сегментам:\n")
print(c_share)


# 2. Критерии предпочтения по сегментам
# unname() нужен, чтобы не получить имена вида CPU.Trading и потом NA при обращении по "CPU"

pref_trading <- c(
  CPU = unname(a["Trading"] / (a["Trading"] + b["Trading"] + c_share["Trading"])),
  RAM = unname(b["Trading"] / (a["Trading"] + b["Trading"] + c_share["Trading"])),
  Storage = unname(c_share["Trading"] / (a["Trading"] + b["Trading"] + c_share["Trading"]))
)

pref_gateways <- c(
  CPU = unname(a["Gateways"] / (a["Gateways"] + b["Gateways"] + c_share["Gateways"])),
  RAM = unname(b["Gateways"] / (a["Gateways"] + b["Gateways"] + c_share["Gateways"])),
  Storage = unname(c_share["Gateways"] / (a["Gateways"] + b["Gateways"] + c_share["Gateways"]))
)

pref_db <- c(
  CPU = unname(a["DB"] / (a["DB"] + b["DB"] + c_share["DB"])),
  RAM = unname(b["DB"] / (a["DB"] + b["DB"] + c_share["DB"])),
  Storage = unname(c_share["DB"] / (a["DB"] + b["DB"] + c_share["DB"]))
)

cat("\nКритерии предпочтения для Trading:\n")
print(round(pref_trading, 4))

cat("\nКритерии предпочтения для Gateways:\n")
print(round(pref_gateways, 4))

cat("\nКритерии предпочтения для DB:\n")
print(round(pref_db, 4))

cat("\nИмена весов Trading:\n")
print(names(pref_trading))

cat("\nИмена весов Gateways:\n")
print(names(pref_gateways))

cat("\nИмена весов DB:\n")
print(names(pref_db))


# 3. Формализация критериев
cat("\nСформулируем критерии предпочтения для каждого сегмента:\n\n")

cat("Trading сегмент:\n")
cat("W1 = Σ(",
    round(pref_trading["CPU"], 2), "*CPUCoresNorm + ",
    round(pref_trading["RAM"], 2), "*RAMNorm + ",
    round(pref_trading["Storage"], 2), "*StorageNorm) * x_i -> max\n\n",
    sep = "")

cat("Gateways сегмент:\n")
cat("W2 = Σ(",
    round(pref_gateways["CPU"], 2), "*CPUCoresNorm + ",
    round(pref_gateways["RAM"], 2), "*RAMNorm + ",
    round(pref_gateways["Storage"], 2), "*StorageNorm) * y_i -> max\n\n",
    sep = "")

cat("DB сегмент:\n")
cat("W3 = Σ(",
    round(pref_db["CPU"], 2), "*CPUCoresNorm + ",
    round(pref_db["RAM"], 2), "*RAMNorm + ",
    round(pref_db["Storage"], 2), "*StorageNorm) * z_i -> max\n\n",
    sep = "")

cat("Критерий верхнего уровня:\n")
cat("S = Σ PriceUSD * v_i -> min\n\n")

cat("Свертка критериев нижнего уровня:\n")
cat("W = W1 + W2 + W3 -> max\n")


# 4. Проверка структуры WW
cat("\nСтолбцы таблицы WW:\n")
print(colnames(WW))

cat("\nКоличество NA в WW по столбцам:\n")
print(colSums(is.na(WW)))


# 5. Коэффициенты целевой функции стоимости
coeffS <- c(FF$Price_USD, FF$Price_USD, FF$Price_USD)

cat("\nКоэффициенты целевой функции стоимости coeffS:\n")
print(coeffS)

cat("\nДлина coeffS:\n")
print(length(coeffS))


# 6. Коэффициенты целевой функции эффективности
coeffW_trading <- pref_trading["CPU"] * WW$CPU_Cores_norm +
                  pref_trading["RAM"] * WW$RAM_GB_norm +
                  pref_trading["Storage"] * WW$Storage_GB_norm

coeffW_gateways <- pref_gateways["CPU"] * WW$CPU_Cores_norm +
                   pref_gateways["RAM"] * WW$RAM_GB_norm +
                   pref_gateways["Storage"] * WW$Storage_GB_norm

coeffW_db <- pref_db["CPU"] * WW$CPU_Cores_norm +
             pref_db["RAM"] * WW$RAM_GB_norm +
             pref_db["Storage"] * WW$Storage_GB_norm

coeffW <- c(coeffW_trading, coeffW_gateways, coeffW_db)

cat("\nКоэффициенты целевой функции эффективности coeffW:\n")
print(coeffW)

cat("\nДлина coeffW:\n")
print(length(coeffW))

cat("\nКоличество NA в coeffW:\n")
print(sum(is.na(coeffW)))

Доли CPU по сегментам:
  Trading  Gateways        DB
0.2941176 0.2941176 0.4117647

Доли RAM по сегментам:
 Trading Gateways       DB
    0.25     0.25     0.50

Доли Storage по сегментам:
  Trading  Gateways        DB
0.1666667 0.1666667 0.6666667

Критерии предпочтения для Trading:
    CPU     RAM Storage
 0.4138  0.3517  0.2345

Критерии предпочтения для Gateways:
    CPU     RAM Storage
 0.4138  0.3517  0.2345

Критерии предпочтения для DB:
    CPU     RAM Storage
 0.2609  0.3168  0.4224

Имена весов Trading:
[1] "CPU"     "RAM"     "Storage"

Имена весов Gateways:
[1] "CPU"     "RAM"     "Storage"

Имена весов DB:
[1] "CPU"     "RAM"     "Storage"

Сформулируем критерии предпочтения для каждого сегмента:

Trading сегмент:
W1 = Σ(0.41*CPUCoresNorm + 0.35*RAMNorm + 0.23*StorageNorm) * x_i -> max

Gateways сегмент:
W2 = Σ(0.41*CPUCoresNorm + 0.35*RAMNorm + 0.23*StorageNorm) * y_i -> max

DB сегмент:
W3 = Σ(0.26*CPUCoresNorm + 0.32*RAMNorm + 0.42*StorageNorm) * z_i -> max

Критерий верхнего уровня:
S = Σ PriceUSD * v_i -> min

Свертка критериев нижнего уровня:
W = W1 + W2 + W3 -> max

Столбцы таблицы WW:
[1] "CPU_Cores_norm"         "CPU_Frequency_GHz_norm" "RAM_GB_norm"
[4] "Storage_GB_norm"        "Price_USD_norm"

Количество NA в WW по столбцам:
        CPU_Cores_norm CPU_Frequency_GHz_norm            RAM_GB_norm
                     0                      0                      0
       Storage_GB_norm         Price_USD_norm
                     0                      0

Коэффициенты целевой функции стоимости coeffS:
  [1]  2568  3690  1353  6015  2028  5957  1615  2037  1764  1735  3670  5593
 [13]  2320  4311  2973  2147  5734  7977  1501  3362  1757  4454  2490  1379
 [25]  2268  2433  5805  6072  1479  2394  1499  1760  1783  1494  6020  2151
 [37]  1542  1486  2148  1193  1956  3198  4792  5067  2831  2185  1993 13265
 [49]  2995  2147  2130  3038  1330  3795  3505  2782  2049  1068  2206  3739
 [61]  1423  1242  3413  2346  1511  2361  2159  2079  3839  1208  3217  1699
 [73]  2383  1204  1570  2059  4270  4329  2519  3072  1553  3245  1625  1483
 [85]  2290  4161  1639  1424  7601  2456  2759  1831  1465  1846  1987  4087
 [97]  2316  4253  1778  2739  1449  1552  1963  4224  1588  1332  2314  3214
[109]  1808  1240  2551  1257  1885  4372  2139  1122  4387  2411  1975  1604
[121]  7538  1666  1382  2674  4744  2254  1613  1935  2698  1328  2799  1429
[133]  1293  1386  4108  1721  2659  6865  3274  1207  1219  3367  2748  2593
[145]  1961  4082  2368  1760  2205  2640  1790  2242  1861  2667  6338 13026
[157]  2760  2788  8962  1588  3433  1610  1802  2180  3288  4465  1917  3306
[169]  2938  2469  2397  1187  2749  2351  6693  2348  2223  2575  1434  1612
[181]  6903  3277  1981  1513  1494  1452  2568  3690  1353  6015  2028  5957
[193]  1615  2037  1764  1735  3670  5593  2320  4311  2973  2147  5734  7977
[205]  1501  3362  1757  4454  2490  1379  2268  2433  5805  6072  1479  2394
[217]  1499  1760  1783  1494  6020  2151  1542  1486  2148  1193  1956  3198
[229]  4792  5067  2831  2185  1993 13265  2995  2147  2130  3038  1330  3795
[241]  3505  2782  2049  1068  2206  3739  1423  1242  3413  2346  1511  2361
[253]  2159  2079  3839  1208  3217  1699  2383  1204  1570  2059  4270  4329
[265]  2519  3072  1553  3245  1625  1483  2290  4161  1639  1424  7601  2456
[277]  2759  1831  1465  1846  1987  4087  2316  4253  1778  2739  1449  1552
[289]  1963  4224  1588  1332  2314  3214  1808  1240  2551  1257  1885  4372
[301]  2139  1122  4387  2411  1975  1604  7538  1666  1382  2674  4744  2254
[313]  1613  1935  2698  1328  2799  1429  1293  1386  4108  1721  2659  6865
[325]  3274  1207  1219  3367  2748  2593  1961  4082  2368  1760  2205  2640
[337]  1790  2242  1861  2667  6338 13026  2760  2788  8962  1588  3433  1610
[349]  1802  2180  3288  4465  1917  3306  2938  2469  2397  1187  2749  2351
[361]  6693  2348  2223  2575  1434  1612  6903  3277  1981  1513  1494  1452
[373]  2568  3690  1353  6015  2028  5957  1615  2037  1764  1735  3670  5593
[385]  2320  4311  2973  2147  5734  7977  1501  3362  1757  4454  2490  1379
[397]  2268  2433  5805  6072  1479  2394  1499  1760  1783  1494  6020  2151
[409]  1542  1486  2148  1193  1956  3198  4792  5067  2831  2185  1993 13265
[421]  2995  2147  2130  3038  1330  3795  3505  2782  2049  1068  2206  3739
[433]  1423  1242  3413  2346  1511  2361  2159  2079  3839  1208  3217  1699
[445]  2383  1204  1570  2059  4270  4329  2519  3072  1553  3245  1625  1483
[457]  2290  4161  1639  1424  7601  2456  2759  1831  1465  1846  1987  4087
[469]  2316  4253  1778  2739  1449  1552  1963  4224  1588  1332  2314  3214
[481]  1808  1240  2551  1257  1885  4372  2139  1122  4387  2411  1975  1604
[493]  7538  1666  1382  2674  4744  2254  1613  1935  2698  1328  2799  1429
[505]  1293  1386  4108  1721  2659  6865  3274  1207  1219  3367  2748  2593
[517]  1961  4082  2368  1760  2205  2640  1790  2242  1861  2667  6338 13026
[529]  2760  2788  8962  1588  3433  1610  1802  2180  3288  4465  1917  3306
[541]  2938  2469  2397  1187  2749  2351  6693  2348  2223  2575  1434  1612
[553]  6903  3277  1981  1513  1494  1452

Длина coeffS:
[1] 558

Коэффициенты целевой функции эффективности coeffW:
  [1]  8.0075293 16.8745244  4.0752533 18.4508791 11.8226601 22.8601466
  [7]  6.1113781  4.2893188  6.1344067  3.3369378 10.9960351 45.6516080
 [13]  5.7501302 24.2394569 25.0310385 17.3987745 45.6516080 40.7553366
 [19]  3.1527094 23.3101045  7.6134407 44.1980055  5.3858785  0.9395651
 [25]  8.7300252 12.2039329 20.2627258 22.8831751  0.9395651  5.7743602
 [31]  6.1344067  2.8186952  8.5317794  4.6577756 21.4065441 15.0474588
 [37]  3.1557131  2.0561496  7.6122392  2.5974208  7.6122392 15.4415475
 [43] 33.1755377 47.8847771 14.9783732  9.0670431  5.7743602 40.7254996
 [49] 17.4448316  5.0518643  4.6335456 18.8778085  2.5974208 35.2709360
 [55] 10.2334895 12.4167968  3.5139573  1.4778325  9.0900717 24.9849814
 [61]  5.5761144  1.8591053 10.9960351 18.8778085  3.8952301  5.0518643
 [67] 13.0113341  7.0551484 21.6420361  1.8591053 18.2922824  4.6335456
 [73] 14.4891666  2.9556650  5.5761144 11.8226601 24.2394569 22.7944651
 [79]  9.4611318 25.1231527  2.0561496 26.4039409  5.5530858  3.1557131
 [85]  4.2893188 42.3188754  8.5317794  1.8591053 24.3610076  9.4611318
 [91]  9.4841604  5.7501302  2.5974208  8.5317794  2.8186952 27.3563218
 [97]  7.2509912 35.2709360  7.0551484  7.2509912  1.6748768  2.4173976
[103]  7.2279627 16.8831351  7.0551484  4.0994834  7.2509912 26.4039409
[109]  1.7021106  1.7021106 18.8778085  2.4173976 10.1836277 43.9767311
[115]  7.2509912  0.3812728 27.2642076 12.0917938  7.6122392  6.4696223
[121] 50.8975129  2.8186952  1.8591053 24.9261084 44.5350234 12.7622252
[127]  2.9556650  9.0900717  7.9832993  1.1438183 19.7901398  3.3369378
[133]  0.0000000  2.5974208 30.9423685  2.8186952 20.3314109 17.3070608
[139] 20.5526853  1.1438183  2.5974208 23.4482759  8.7300252 14.4891666
[145] 11.5335015 22.7858545 12.2039329  4.0752533  8.7300252 17.3987745
[151]  4.0752533  8.7300252  7.2509912  9.4841604 19.9044816 58.6206897
[157] 14.6413553 16.9193800 42.2331691  3.1799431 22.0062878  6.1344067
[163]  7.0539469  5.0518643 19.1197084  9.5182026 11.4874444 18.3972125
[169] 10.9619929 12.9664784  8.0075293  1.1438183 12.4398254  7.2279627
[175] 31.7271417 12.0457367  2.8186952 24.9261084  0.9395651  3.5339821
[181] 50.1349674 23.9144539 12.0917938  6.1344067  3.5139573  5.5761144
[187]  8.0075293 16.8745244  4.0752533 18.4508791 11.8226601 22.8601466
[193]  6.1113781  4.2893188  6.1344067  3.3369378 10.9960351 45.6516080
[199]  5.7501302 24.2394569 25.0310385 17.3987745 45.6516080 40.7553366
[205]  3.1527094 23.3101045  7.6134407 44.1980055  5.3858785  0.9395651
[211]  8.7300252 12.2039329 20.2627258 22.8831751  0.9395651  5.7743602
[217]  6.1344067  2.8186952  8.5317794  4.6577756 21.4065441 15.0474588
[223]  3.1557131  2.0561496  7.6122392  2.5974208  7.6122392 15.4415475
[229] 33.1755377 47.8847771 14.9783732  9.0670431  5.7743602 40.7254996
[235] 17.4448316  5.0518643  4.6335456 18.8778085  2.5974208 35.2709360
[241] 10.2334895 12.4167968  3.5139573  1.4778325  9.0900717 24.9849814
[247]  5.5761144  1.8591053 10.9960351 18.8778085  3.8952301  5.0518643
[253] 13.0113341  7.0551484 21.6420361  1.8591053 18.2922824  4.6335456
[259] 14.4891666  2.9556650  5.5761144 11.8226601 24.2394569 22.7944651
[265]  9.4611318 25.1231527  2.0561496 26.4039409  5.5530858  3.1557131
[271]  4.2893188 42.3188754  8.5317794  1.8591053 24.3610076  9.4611318
[277]  9.4841604  5.7501302  2.5974208  8.5317794  2.8186952 27.3563218
[283]  7.2509912 35.2709360  7.0551484  7.2509912  1.6748768  2.4173976
[289]  7.2279627 16.8831351  7.0551484  4.0994834  7.2509912 26.4039409
[295]  1.7021106  1.7021106 18.8778085  2.4173976 10.1836277 43.9767311
[301]  7.2509912  0.3812728 27.2642076 12.0917938  7.6122392  6.4696223
[307] 50.8975129  2.8186952  1.8591053 24.9261084 44.5350234 12.7622252
[313]  2.9556650  9.0900717  7.9832993  1.1438183 19.7901398  3.3369378
[319]  0.0000000  2.5974208 30.9423685  2.8186952 20.3314109 17.3070608
[325] 20.5526853  1.1438183  2.5974208 23.4482759  8.7300252 14.4891666
[331] 11.5335015 22.7858545 12.2039329  4.0752533  8.7300252 17.3987745
[337]  4.0752533  8.7300252  7.2509912  9.4841604 19.9044816 58.6206897
[343] 14.6413553 16.9193800 42.2331691  3.1799431 22.0062878  6.1344067
[349]  7.0539469  5.0518643 19.1197084  9.5182026 11.4874444 18.3972125
[355] 10.9619929 12.9664784  8.0075293  1.1438183 12.4398254  7.2279627
[361] 31.7271417 12.0457367  2.8186952 24.9261084  0.9395651  3.5339821
[367] 50.1349674 23.9144539 12.0917938  6.1344067  3.5139573  5.5761144
[373]  7.4433167 13.0333788  5.6102611 17.6473983  7.4534161 22.1290425
[379]  7.0447479  4.2064334 10.5467426  2.5501187 10.5341182 32.2739700
[385]  7.1186905 19.3783770 29.7364757 17.4973489 32.2739700 57.8231293
[391]  2.4401065 21.2240570  6.2898118 29.6556799  4.4513458  1.1895745
[397]  7.2954314  8.1401808 17.4504584 25.6310371  1.1895745  5.4320774
[403] 10.5467426  3.5687234 11.9072868  4.4264578 19.5107523 23.1407940
[409]  5.1813939  2.1951941 11.4784196  4.6785841 11.4784196 24.2942988
[415] 35.4744231 34.2852093 12.6348100  8.9081019  5.4320774 38.2189567
[421] 24.5013382  5.5799626  6.1130709 13.2404181  4.6785841 49.6894410
[427]  9.1605889 11.9249609  2.3661639  0.9316770 12.4100966 22.7324864
[433] 10.0439327  1.6184417 10.5341182 13.2404181  3.0529285  5.5799626
[439] 21.7063071  5.7870020 14.6997930  1.6184417 11.6829340  6.1130709
[445] 22.6379841  1.8633540 10.0439327  7.4534161 19.3783770 19.6741475
[451] 10.0616068 43.7444543  2.1951941 44.0993789  6.5419381  5.1813939
[457]  4.2064334 27.2765310 11.9072868  1.6184417 26.5627142 10.0616068
[463] 13.5636015  7.1186905  4.6785841 11.9072868  3.5687234 45.7556936
[469] 11.5523622 49.6894410  5.7870020 11.5523622  1.5084295  2.1212515
[475]  8.0503675 15.9474394  5.7870020  3.9236479 11.5523622 44.0993789
[481]  2.5631037  2.5631037 13.2404181  2.1212515  9.9137216 30.7655406
[487] 11.5523622  0.6867646 31.7477150 21.2774399 11.4784196  4.2295179
[493] 35.6893977  3.5687234  1.6184417 43.1677019 31.2683504  8.6429906
[499]  1.8633540 12.4100966  9.1299298  2.0602939 13.3753183  2.5501187
[505]  0.0000000  4.6785841 33.4631838  3.5687234 15.8587083 15.5871044
[511] 14.7488476  2.0602939  4.6785841 42.2360248  7.2954314 22.6379841
[517] 20.7746301 16.7600869  8.1401808  5.6102611  7.2954314 17.4973489
[523]  5.6102611  7.2954314 11.5523622 13.5636015 20.2656885 73.9130435
[529] 11.0221395 25.2259759 58.7548063  3.4947807 17.3671377 10.5467426
[535] 10.9756098  5.5799626 26.0097676  9.6024412 13.7706408 26.1576529
[541] 14.4952785  9.5137100  7.4433167  2.0602939 15.4269555  8.0503675
[547] 27.7191046 14.2734506  3.5687234 43.1677019  1.1895745  3.1268711
[553] 34.3158684 28.7308561 21.2774399 10.5467426  2.3661639 10.0439327

Длина coeffW:
[1] 558

Количество NA в coeffW:
[1] 0

In [ ]:
install.packages("lpSolve")
library(lpSolve)

# Количество Парето-оптимальных альтернатив
n <- nrow(FF)

cat("Количество альтернатив в одном сегменте:", n, "\n")
cat("Общее число переменных в задаче:", 3 * n, "\n")

Installing package into ‘/usr/local/lib/R/site-library’
(as ‘lib’ is unspecified)

Количество альтернатив в одном сегменте: 186
Общее число переменных в задаче: 558

In [ ]:
# ========================================
# Задача 1. Максимизация суммарной эффективности
# W = W1 + W2 + W3 -> max
# ========================================

objective.in<-coeffW
const.mat<-matrix(c(coeffS,
                  c(rep(1,n),rep(0,n),rep(0,n)),
                  c(rep(0,n),rep(1,n),rep(0,n)),
                  c(rep(0,n),rep(0,n),rep(1,n)),
                  c(rep(1,n),rep(0,n),rep(0,n)),
                  c(rep(0,n),rep(1,n),rep(0,n)),
                  c(rep(0,n),rep(0,n),rep(1,n))), nrow=7, byrow=TRUE)
const.dir<-c("<=",">=",">=",">=","<=","<=","<=")
const.rhs<-c(450000, 6,3,3, 10,5,5)
Res<-lp("max", objective.in, const.mat, const.dir, const.rhs, all.int=TRUE)

Res$solution

S<-function(p){return(sum(coeffS*p))}
W<-function(p){return(sum(coeffW*p))}

S(Res$solution)
W(Res$solution)

cat("Статус решения задачи W -> max:", Res_W$status, "\n")
cat("Решение:\n")
print(Res_W$solution)

  [1]  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
 [26]  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
 [51]  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
 [76]  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
[101]  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
[126]  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
[151]  0  0  0  0  0 10  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
[176]  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
[201]  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
[226]  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
[251]  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
[276]  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
[301]  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
[326]  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  5  0  0  0  0  0  0  0  0
[351]  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
[376]  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
[401]  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
[426]  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
[451]  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
[476]  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
[501]  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
[526]  0  0  5  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
[551]  0  0  0  0  0  0  0  0

[1] 260520

[1] 1248.876

Статус решения задачи W -> max: 0
Решение:
  [1]  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
 [26]  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
 [51]  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
 [76]  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
[101]  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
[126]  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
[151]  0  0  0  0  0 10  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
[176]  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
[201]  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
[226]  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
[251]  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
[276]  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
[301]  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
[326]  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  5  0  0  0  0  0  0  0  0
[351]  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
[376]  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
[401]  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
[426]  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
[451]  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
[476]  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
[501]  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
[526]  0  0  5  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
[551]  0  0  0  0  0  0  0  0

In [ ]:
# ========================================
# Функции расчета критериев
# ========================================

S <- function(p) {
  return(sum(coeffS * p, na.rm = TRUE))
}

W <- function(p) {
  return(sum(coeffW * p, na.rm = TRUE))
}

# на всякий случай уберём NA из решения
sol <- Res_W$solution
sol[is.na(sol)] <- 0

cat("Значение критерия стоимости S:\n")
print(S(sol))

cat("\nЗначение критерия эффективности W:\n")
print(W(sol))

Значение критерия стоимости S:
[1] 260520

Значение критерия эффективности W:
[1] 1248.876

После решения первой задачи получаем максимальное значение интегрального критерия эффективности \(W\) при выполнении ограничений по бюджету и количеству узлов в каждом сегменте.

Далее применяется метод последовательных уступок: допускается небольшое снижение эффективности, после чего оптимизируется критерий стоимости \(S\).

In [ ]:
# ========================================
# Метод последовательных уступок
# Допускаем снижение эффективности на 5%
# ========================================

W_star <- W(Res_W$solution)
eff_drop <- 0.05
W_limit <- (1 - eff_drop) * W_star

cat("Максимальное значение эффективности W* =", W_star, "\n")
cat("Допустимое значение после уступки W_limit =", W_limit, "\n")

Максимальное значение эффективности W* = 1248.876
Допустимое значение после уступки W_limit = 1186.432

In [ ]:
objective.in<-coeffS
const.mat<-matrix(c(coeffW,
                  c(rep(1,n),rep(0,n),rep(0,n)),
                  c(rep(0,n),rep(1,n),rep(0,n)),
                  c(rep(0,n),rep(0,n),rep(1,n)),
                  c(rep(1,n),rep(0,n),rep(0,n)),
                  c(rep(0,n),rep(1,n),rep(0,n)),
                  c(rep(0,n),rep(0,n),rep(1,n))), nrow=7, byrow=TRUE)
const.dir<-c(">=",">=",">=",">=","<=","<=","<=")
const.rhs<-c(W_limit, 6,3,3, 10,5,5)
Res<-lp("min", objective.in, const.mat, const.dir, const.rhs, all.int=TRUE)

Res$solution

S(Res$solution)
W(Res$solution)

  [1] 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 [38] 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 [75] 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
[112] 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
[149] 0 0 0 0 0 0 0 9 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
[186] 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
[223] 0 0 0 0 0 0 0 4 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
[260] 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
[297] 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
[334] 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0
[371] 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
[408] 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
[445] 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
[482] 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
[519] 0 0 0 0 0 0 0 0 0 5 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
[556] 0 0 0

[1] 214602

[1] 1186.71

In [ ]:
cat("Значение критерия стоимости S после уступки:\n")
print(S(Res_S$solution))

cat("\nЗначение критерия эффективности W после уступки:\n")
print(W(Res_S$solution))

Значение критерия стоимости S после уступки:
[1] 214602

Значение критерия эффективности W после уступки:
[1] 1186.71

In [ ]:
# ========================================
# Расшифровка решения по сегментам
# ========================================

sol <- Res_S$solution

x_trading <- sol[1:n]
x_gateways <- sol[(n + 1):(2 * n)]
x_db <- sol[(2 * n + 1):(3 * n)]

RES_Trading <- data.frame(ID = rownames(FF), FF, Count = x_trading)
RES_Trading <- RES_Trading[RES_Trading$Count > 0, ]

RES_Gateways <- data.frame(ID = rownames(FF), FF, Count = x_gateways)
RES_Gateways <- RES_Gateways[RES_Gateways$Count > 0, ]

RES_DB <- data.frame(ID = rownames(FF), FF, Count = x_db)
RES_DB <- RES_DB[RES_DB$Count > 0, ]

cat("========================================\n")
cat("СЕГМЕНТ TRADING\n")
cat("========================================\n")
print(RES_Trading)

cat("\n========================================\n")
cat("СЕГМЕНТ GATEWAYS\n")
cat("========================================\n")
print(RES_Gateways)

cat("\n========================================\n")
cat("СЕГМЕНТ DB\n")
cat("========================================\n")
print(RES_DB)

========================================
СЕГМЕНТ TRADING
========================================
             ID CPU_Frequency_GHz CPU_Cores RAM_GB Storage_GB Price_USD Count
PC-0210 PC-0210              1.76        64    256       1000      5067     1
PC-0790 PC-0790              4.98         8   2048       8000     13026     9

========================================
СЕГМЕНТ GATEWAYS
========================================
             ID CPU_Frequency_GHz CPU_Cores RAM_GB Storage_GB Price_USD Count
PC-0210 PC-0210              1.76        64    256       1000      5067     4
PC-0955 PC-0955              2.82        64    512        256      6903     1

========================================
СЕГМЕНТ DB
========================================
             ID CPU_Frequency_GHz CPU_Cores RAM_GB Storage_GB Price_USD Count
PC-0790 PC-0790              4.98         8   2048       8000     13026     5

In [ ]:
# ========================================
# Итоговые характеристики по сегментам
# ========================================

calc_totals <- function(df) {
  if (nrow(df) == 0) {
    return(data.frame(
      Nodes = 0,
      CPU_Cores = 0,
      RAM_GB = 0,
      Storage_GB = 0,
      Price_USD = 0
    ))
  }

  data.frame(
    Nodes = sum(df$Count),
    CPU_Cores = sum(df$CPU_Cores * df$Count),
    RAM_GB = sum(df$RAM_GB * df$Count),
    Storage_GB = sum(df$Storage_GB * df$Count),
    Price_USD = sum(df$Price_USD * df$Count)
  )
}

tot_trading <- calc_totals(RES_Trading)
tot_gateways <- calc_totals(RES_Gateways)
tot_db <- calc_totals(RES_DB)

summary_segments <- rbind(
  cbind(Segment = "Trading", tot_trading),
  cbind(Segment = "Gateways", tot_gateways),
  cbind(Segment = "DB", tot_db)
)

cat("Итоговые характеристики по сегментам:\n")
print(summary_segments)

Итоговые характеристики по сегментам:
   Segment Nodes CPU_Cores RAM_GB Storage_GB Price_USD
1  Trading    10       136  18688      73000    122301
2 Gateways     5       320   1536       4256     27171
3       DB     5        40  10240      40000     65130

In [ ]:
# ========================================
# Общий итог по инфраструктуре
# ========================================

total_nodes <- sum(summary_segments$Nodes)
total_cpu <- sum(summary_segments$CPU_Cores)
total_ram <- sum(summary_segments$RAM_GB)
total_storage <- sum(summary_segments$Storage_GB)
total_price <- sum(summary_segments$Price_USD)

cat("========================================\n")
cat("ИТОГОВАЯ ИНФРАСТРУКТУРА HFT\n")
cat("========================================\n\n")

print(summary_segments)

cat("\n--- ОБЩИЙ ИТОГ ---\n")
cat("Всего узлов:", total_nodes, "\n")
cat("Всего CPU ядер:", total_cpu, "\n")
cat("Всего RAM (ГБ):", total_ram, "\n")
cat("Всего Storage (ГБ):", total_storage, "\n")
cat("Общая стоимость (USD):", total_price, "\n")

========================================
ИТОГОВАЯ ИНФРАСТРУКТУРА HFT
========================================

   Segment Nodes CPU_Cores RAM_GB Storage_GB Price_USD
1  Trading    10       136  18688      73000    122301
2 Gateways     5       320   1536       4256     27171
3       DB     5        40  10240      40000     65130

--- ОБЩИЙ ИТОГ ---
Всего узлов: 20
Всего CPU ядер: 496
Всего RAM (ГБ): 30464
Всего Storage (ГБ): 117256
Общая стоимость (USD): 214602

### Вывод по второй части

Во второй части была решена задача двухуровневой оптимизации инфраструктуры криптовалютной биржи. На первом этапе максимизировался интегральный критерий эффективности \(W\), отражающий качество выбранных конфигураций в сегментах Trading, Gateways и DB. На втором этапе методом последовательных уступок минимизировалась суммарная стоимость инфраструктуры \(S\) при допустимом снижении эффективности на 5%.

В результате был получен конкретный состав инфраструктуры по сегментам, определено количество узлов каждого типа и рассчитаны итоговые суммарные характеристики системы: число узлов, общий объем CPU, RAM, Storage и полная стоимость.